"""add default_workspace to user

Revision ID: 70a90149c433
Revises: b1stripe01
Create Date: 2026-10-05 22:20:10.111856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a90149c433'
down_revision: Union[str, Sequence[str], None] = 'b1stripe01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite doesn't support adding NOT NULL column with default
    # Add as nullable first, update existing rows, then alter to NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_workspace', sa.String(length=50), nullable=True))

    # Set default for existing rows
    op.execute("UPDATE users SET default_workspace = 'academic' WHERE default_workspace IS NULL")

    # Now make it non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('default_workspace', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_workspace')

    # ### end Alembic commands ###
